const data = [
  {
    id: 1,
    Name: "chevrolet chevelle malibu",
    Miles_per_Gallon: 18,
    Cylinders: 8,
    Displacement: 307,
    Horsepower: 130,
    Weight_in_lbs: 3504,
    Acceleration: 12,
    Year: "1970-01-01",
    Origin: "USA",
  },
  {
      "id": 3,
      "status": "processing",
      "supplier": "ed",
      "item_index": "{total_item}/{j+1}/1",
      "color": "Sari Altin",
      "qty": "Imza",
      "size": "7CM",
      "start": "ortada",
      "space": "-",
      "length": "40cm",
      "type": "14K KOLYE IMZA",
      "explanation": "*** 14K ALTIN ***\n",
      "note": "",
      "is_invoiced": null,
      "is_ready": false,
      "ready_date": null,
      "tracking_code": null,
      "creation_tsz": null,
      "buyer": null,
      "seller_user_id": null,
      "message_from_buyer": null,
      "sku": null,
      "personalization": null,
      "last_updated": "2021-01-19T07:10:32.884178",
      "created_date": "2021-01-12T20:40:22.268444",
      "receipt": 1898902368,
      "transaction": 2238665328
  },
];

export default data;
